// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>;
}
